[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0
extra_scripts =
  pre:scripts/pre_upload_guard.py

lib_deps =
  jgromes/RadioLib@^7.1.1
  bblanchon/ArduinoJson@^7.0.0

build_flags =
  -D LORA_SX126X_SCK=5
  -D LORA_SX126X_MISO=3
  -D LORA_SX126X_MOSI=6
  -D LORA_SX126X_CS=7
  -D LORA_SX126X_RESET=8
  -D LORA_SX126X_DIO1=47
  -D LORA_SX126X_BUSY=48
